### ISSUE TITLE
No storage option exists to persist the session, which may result in unexpected behavior when using auth.

### ISSUE THREAD

**Issue by CareTiger** [nuxt-modules/supabase#188]
seeing this warning/information on starting the dev server. Not sure of the implications and what action needs to be taken. FYI - discussion thread on [Supabase - Discord server](https://discord.com/channels/839993398554656828/1113542747643715584/1113542747643715584)  

```No storage option exists to persist the session, which may result in unexpected behavior when using auth. If you want to set persistSession to true, please provide a storage option or you may set persistSession to false to disable this warning.```

my nuxi info- 
```
- Operating System: Darwin
- Node Version:     v19.8.1
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  npm@9.5.1
- Builder:          vite
- User Config:      typescript, colorMode, app, plugins, modules, googleFonts, routeRules, runtimeConfig, nitro, devtools, image, vite
- Runtime Modules:  @storyblok/nuxt@5.4.7, @nuxt/image-edge@1.0.0-28092818.5c21f4c, @nuxt/devtools@0.5.5, @nuxtjs/supabase@0.3.5, @nuxtjs/google-fonts@3.0.1, @formkit/nuxt@0.17.2, @nuxthq/ui@2.2.1, @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.1, @vee-validate/nuxt@4.9.6
- Build Modules:    -
```

**Comment by maximilian-schwarz** [comment]
This warning is coming from the "@supabase/supabase-js" package. Because the "persistSession" is not set.
For more information: https://supabase.com/docs/reference/javascript/release-notes

Add to your nuxt.config.ts the following:

```js
supabase: {
  client: {
      auth: {
          persistSession: false //or true
      }
  }
}
```

After this change the warning is gone.

**Comment by mitjans** [comment]
@maximilian-schwarz what are the implications of setting `persistSession` to true or false?
What was the default behaviour before?

**Comment by lipecss** [comment]
im still getting this alert, ive already set `supabase: {
  client: {
      auth: {
          persistSession: false //or true
      }
  }
}` but nothing

**Comment by j4w8n** [comment]
> This warning is coming from the "@supabase/supabase-js" package. Because the "persistSession" is not set.
> For more information: https://supabase.com/docs/reference/javascript/release-notes
> 
> Add to your nuxt.config.ts the following:
> 
> ```js
> supabase: {
>   client: {
>       auth: {
>           persistSession: false //or true
>       }
>   }
> }
> ```
> 
> After this change the warning is gone.

You might do some thorough testing with that. I haven't delved into the code, but the library may be relying on this being true for the browser client.

CC: @mitjans

**Comment by j4w8n** [comment]
Yeah, this line would need persistSession to be true for the browser client.

https://github.com/nuxt-modules/supabase/blob/main/src/runtime/plugins/supabase.client.ts#L32

And if you're calling getSession at all in your own code, it would fail as well.

**Comment by j4w8n** [comment]
Looks like this was resolved in release 0.3.6

**Comment by CareTiger** [comment]
resolved in release 0.3.6.

**Comment by tidusvn05** [comment]
same problem on latest version.

------------------------------
- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      ssr, nitro, experimental, runtimeConfig, app, modules, piniaPersistedstate, css, tailwindcss, supabase
- Runtime Modules:  @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.1, @nuxtjs/supabase@0.3.6, @nuxtjs/tailwindcss@6.7.0, @vueuse/nuxt@10.1.2, nuxt-icon@0.4.1
- Build Modules:    -
------------------------------

**Comment by j4w8n** [comment]
> same problem on latest version: 0.3.6
> 
> ![Screenshot 2023-06-03 at 12 42 38](https://github.com/nuxt-modules/supabase/assets/2610894/bba02710-7d86-4a48-a8de-75b072d5f1bb)
> 
> ------------------------------
> - Operating System: Darwin
> - Node Version:     v18.16.0
> - Nuxt Version:     3.5.2
> - Nitro Version:    2.4.1
> - Package Manager:  yarn@1.22.19
> - Builder:          vite
> - User Config:      ssr, nitro, experimental, runtimeConfig, app, modules, piniaPersistedstate, css, tailwindcss, supabase
> - Runtime Modules:  @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.1, @nuxtjs/supabase@0.3.6, @nuxtjs/tailwindcss@6.7.0, @vueuse/nuxt@10.1.2, nuxt-icon@0.4.1
> - Build Modules:    -
> ------------------------------
> 

@tidusvn05 can you try 0.3.7? Someone found another portion of code which needed changed.

**Comment by tidusvn05** [comment]
Thank for your feedback.

i was upgrade, but problem still exist.

![Screenshot 2023-06-25 at 15 49 08](https://github.com/nuxt-modules/supabase/assets/2610894/def8fbea-e253-44ad-8bfd-d7f10c7a3851)

**Comment by j4w8n** [comment]
@tidusvn05 do you mind creating a new issue and showing your code for creating all of your supabase clients?

**Comment by jetlej** [comment]
I'm still getting this error despite putting the code in my nuxt.config.js. 

------------------------------
- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.10
- Builder:          vite
- User Config:      app, runtimeConfig, components, css, plugins, buildModules, modules, colorMode, supabase, target, build
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @nuxtjs/color-mode@3.3.0, @vueuse/nuxt@10.2.1
- Build Modules:    -

**Comment by didim1** [comment]
const supabase = createClient<Database>(
  process.env.NEXT_PUBLIC_SUPABASE_URL as string,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY as string,
  { auth: { persistSession: false } }
);

hi im from the future :3

**Comment by jetlej** [comment]
@didim1 yes that did the trick! So you need to set it in each file you're using createClient() in, NOT in the nuxt.config.js file

**Comment by Rohianon** [comment]
@didim1 it really worked indeed. Thanks for this.

**Comment by wiesson** [comment]
Can anyone explain what `persistSession` does? In which case does it persist the session? Whats better for me, true or false?

**Comment by j4w8n** [comment]
> Can anyone explain what `persistSession` does? In which case does it persist the session? Whats better for me, true or false?

When `true`, it uses a storage implementation supported by supabase - whether built-in or custom; which holds auth info.

When `false`, it uses memory to hold this info.

**Comment by MariuzM** [comment]
But when its true or not even used it stores the token in localStorage but why i'm still getting this error? Setting to false does not make sense because you wont get your token in localStorage

**Comment by j4w8n** [comment]
> But when its true or not even used it stores the token in localStorage but why i'm still getting this error? Setting to false does not make sense because you wont get your token in localStorage

This would be unusual. Possible, I'm sure. Would need to see some code.

**Comment by MariuzM** [comment]
Or maybe i'm wrong im still testing this, damn so confusing

**Comment by wiesson** [comment]
I'm also using Nextjs and I also find it confusing 😅

**Comment by MariuzM** [comment]
So noticed, that because i have createClient not in useEffect then i get this issue and it does not matter that i have set component as client, but when i add this createClient in useEffect then it works fine, so go figure. Next.js is really becoming unstable

**Comment by MariuzM** [comment]
I have tested this on SolidStart getting same issue

**Comment by toddsampson** [comment]
I had the same issue and managed to get it working. I saw in another post related to running Supabase locally that there was an issue with supabase/studio:0.23.06. As such, if you fork https://github.com/supabase/cli and change line 23 in `internal/utils/misc.go` from `StudioImage = "supabase/studio:v0.23.06"` to `StudioImage = "supabase/studio`, run `go build -o supabase .` to build the binary file and then copy it over the existing `node_modules/supabase/bin/supabase` in your project and you should be good to go. Be sure to run `npx supabase stop --no-backup` before you run `npx supabase start` again. Not a real "fix" but it should get you up-and-running

Feel free to grab the updated binary or source from my fork to build it yourself: https://github.com/toddsampson/cli

**Comment by louis030195** [comment]
This is really annoying because it's unclear whether it crashes the code or not, make debugging very painful

I use it in `/app/something/router.ts`:
```ts
import { Database } from '@/types_db';
import { createClient } from '@supabase/supabase-js';

export const runtime = 'edge'


const supabase = createClient<Database>(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_KEY!,
);
export async function GET(req: Request) {

}
```

Such a mess to know which client use in different context, got to try 10 different ways to create the client both in local and deployed on vercel and see if it work or not 😆😭

**Comment by j4w8n** [comment]
@louis030195 based on what I see in your code, you're running the client on the server-side. And since you're not using auth helpers here, or custom storage, you should be setting these three auth options for your client.

```js
const options = {
  auth: {
    persistSession: false,
    autoRefreshToken: false,
    detectSessionInUrl: false
  }
}
```
